services:
  # =======================
  # INFRASTRUCTURE
  # =======================
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    command: ["postgres", "-c", "wal_level=logical"]
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # ✅ NEW: Redis for Inventory Read Model
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data # Persist cache on restart
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_INTERNAL://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    healthcheck:
      test: ["CMD-SHELL", "/opt/kafka/bin/kafka-broker-api-versions.sh --bootstrap-server localhost:9092"]
      interval: 10s
      timeout: 5s
      retries: 5

  connect:
    image: debezium/connect:2.7.3.Final
    container_name: kafka-connect
    ports:
      - "8083:8083"
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_started
    environment:
      BOOTSTRAP_SERVERS: kafka:29092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: my_connect_configs
      OFFSET_STORAGE_TOPIC: my_connect_offsets
      STATUS_STORAGE_TOPIC: my_connect_statuses
      CONFIG_STORAGE_REPLICATION_FACTOR: 1
      OFFSET_STORAGE_REPLICATION_FACTOR: 1
      STATUS_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_REST_ADVERTISED_HOST_NAME: connect
      CONNECT_REST_PORT: 8083
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8080:8080"
    depends_on:
      - kafka
      - connect
    environment:
      KAFKA_CLUSTERS_0_NAME: local-kafka
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME: debezium
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS: http://connect:8083

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

  # =======================
  # MICROSERVICES
  # =======================
  user-service:
    build:
      context: .
      dockerfile: ./services/user-service/Dockerfile
      target: builder
    container_name: user-service
    volumes:
      - ./services/user-service:/app/services/user-service
      - /app/services/user-service/node_modules
    env_file:
      - ./services/user-service/.env
    environment:
      KAFKA_BROKERS: kafka:29092
      DB_HOST: postgres
      OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4318/v1/traces
      OTEL_SERVICE_NAME: user-service 
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_started
    ports:
      - "3000:3000"
    command: ["pnpm", "run", "dev"]

  order-service:
    build:
      context: .
      dockerfile: ./services/order-service/Dockerfile
      target: builder
    container_name: order-service
    volumes:
      - ./services/order-service:/app/services/order-service
      - /app/services/order-service/node_modules
    env_file:
      - ./services/order-service/.env
    environment:
      KAFKA_BROKERS: kafka:29092
      DB_HOST: postgres
      OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4318/v1/traces
      OTEL_SERVICE_NAME: order-service
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_started
    ports:
      - "3001:3001"
    command: ["pnpm", "run", "dev"]
    

  payment-service:
    build:
      context: .
      dockerfile: ./services/payment-service/Dockerfile
      target: builder
    container_name: payment-service
    volumes:
      - ./services/payment-service:/app/servicse/payment-service
      - /app/services/payment-service/node_modules
    env_file:
      - ./services/payment-service/.env
    environment:
      KAFKA_BROKERS: kafka:29092
      DB_HOST: postgres
      OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4318/v1/traces
      OTEL_SERVICE_NAME: payment-service 
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_started
    ports:
      - "3002:3002"
    command: ["pnpm", "run", "dev"]

  inventory-service: 
    build:
      context: .
      dockerfile: ./services/inventory-service/Dockerfile
      target: builder
    container_name: inventory-service
    volumes:
      - ./services/inventory-service:/app/services/inventory-service
      - /app/services/inventory-service/node_modules
    env_file:
      - ./services/inventory-service/.env
    environment:
      KAFKA_BROKERS: kafka:29092
      DB_HOST: postgres
      # ✅ NEW: Point to the Redis Service
      REDIS_HOST: redis 
      REDIS_PORT: 6379
      OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4318/v1/traces
      OTEL_SERVICE_NAME: inventory-service
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_started
      # ✅ NEW: Wait for Redis to be ready
      redis:
        condition: service_healthy
    ports:
      - "3003:3003"

  # =======================
  # INITIALIZATION
  # =======================
  connector-init:
    image: curlimages/curl:latest
    container_name: connector-init
    volumes:
      - ./scripts:/scripts
    entrypoint: >
      /bin/sh -c "
        echo 'Waiting for Kafka Connect to start...';
        while [ $$(curl -s -o /dev/null -w '%{http_code}' http://connect:8083/connectors) -ne 200 ]; do
          sleep 5;
        done;
        echo 'Kafka Connect is up! Registering connectors...';
        for f in /scripts/*.json; do
          echo \"Registering $$f...\";
          curl -X POST -H 'Content-Type: application/json' --data @$$f http://connect:8083/connectors;
          echo \"\n\";
        done;
        echo 'All connectors processed. Success!';"
    depends_on:
      connect:
        condition: service_started

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "16686:16686" # Jaeger UI
      - "4318:4318"   # OTLP HTTP (Collector)
    environment:
      - COLLECTOR_OTLP_ENABLED=true

# =======================
# VOLUMES
# =======================
volumes:
  pgdata:
  redis_data: # ✅ NEW: Volume for Redis persistence