# .github/workflows/user-service-cd.yaml
name: order-service-cd

on:
  workflow_run:
    workflows: ["order-service-cd"]
    types:
      - completed
  
    

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success'  && github.event.workflow_run.head_branch == 'main'}}

    steps:
      - name: Checkout GitOps repo
        uses: actions/checkout@v4
        with:
          repository: skymonil/event-microservice-gitops
          token: ${{ secrets.GITOPS_TOKEN }}
          path: gitops

      - name: Update image tag in dev manifest
        run: |
          NEW_TAG=${{ github.event.workflow_run.head_sha }}
          
          sed -i -E "s|(image:\s*skymonil/order-service:).*|\1${NEW_TAG}|" \
          gitops/services/order-service/rollout.yaml

      - name: Commit & push to GitOps repo
        run: |
          cd gitops
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add services/order-service/rollout.yaml
          git commit -m "Deploy order-service ${{ github.event.workflow_run.head_sha }} to dev" || echo "No changes to commit" --allow-empty
          git push
