# .github/workflows/user-service-cd.yaml
name: user-service-cd
env:
  SERVICE_NAME: user-service

on:
  workflow_run:
    workflows: ["user-service-ci"]
    types:
      - completed
  
    

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success'  && github.event.workflow_run.head_branch == 'main'}}

    steps:
      - name: Checkout GitOps repo
        uses: actions/checkout@v4
        with:
          repository: skymonil/event-microservice-gitops
          token: ${{ secrets.GITOPS_TOKEN }}
          path: gitops

      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Download image digest artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{env.SERVICE_NAME}}-digest
          run-id: ${{ github.event.workflow_run.id }}

      - name: Update Image Digest in Dev Overlay
        # ðŸŸ¢ Navigate specifically to the DEV overlay folder
        working-directory: gitops/services/${{env.SERVICE_NAME}}/overlays/dev
        run: |
          DIGEST=$(cat ../../../../image-digest.txt)
          kustomize edit set image skymonil/${{ env.SERVICE_NAME }}=$DIGEST
          

      - name: Commit & push to GitOps repo
        run: |
          DIGEST=$(cat image-digest.txt)
          cd gitops
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add services/${{env.SERVICE_NAME}}/overlays/dev/kustomization.yaml
          git commit -m "Deploy ${{ env.SERVICE_NAME }} ${{ github.event.workflow_run.head_sha }} to dev" || echo "No changes to commit" --allow-empty
          git push
