# .github/workflows/user-service-cd.yaml
name: user-service-cd

on:
  workflow_run:
    workflows: ["user-service-ci"]
    types:
      - completed
  push:
    branches:
      - main
    paths:
      - "services/user-service/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success'  && github.event.workflow_run.head_branch == 'main'}}

    steps:
      - name: Checkout GitOps repo
        uses: actions/checkout@v4
        with:
          repository: skymonil/event-microservice-gitops
          token: ${{ secrets.GITOPS_TOKEN }}
          path: gitops

      - name: Update image tag in dev manifest
        run: |
          sed -i "s|image: skymonil/user-service:.*|image: skymonil/user-service:${{ github.sha }}|g" \
          gitops/environments/dev/apps/user-service.yaml

      - name: Commit & push to GitOps repo
        run: |
          cd gitops
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add environments/dev/apps/user-service.yaml
          git commit -m "Deploy user-service ${{ github.sha }} to dev"
          git push
