# .github/workflows/user-service-cd.yaml
name: user-service-cd

on:
  workflow_run:
    workflows: ["user-service-ci"]
    types:
      - completed
  
    

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success'  && github.event.workflow_run.head_branch == 'main'}}

    steps:
      - name: Checkout GitOps repo
        uses: actions/checkout@v4
        with:
          repository: skymonil/event-microservice-gitops
          token: ${{ secrets.GITOPS_TOKEN }}
          path: gitops

      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Update Image Tag in Dev Overlay
        # ðŸŸ¢ Navigate specifically to the DEV overlay folder
        working-directory: gitops/services/user-service/overlays/dev
        run: |
          NEW_TAG=${{ github.event.workflow_run.head_sha }}
          kustomize edit set image skymonil/user-service=skymonil/user-service:$NEW_TAG

      - name: Commit & push to GitOps repo
        run: |
          cd gitops
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add services/user-service/overlays/dev/kustomization.yaml
          git commit -m "Deploy user-service ${{ github.event.workflow_run.head_sha }} to dev" || echo "No changes to commit" --allow-empty
          git push
