name: user-service-ci

on:
  push:
    branches:
      - main
      - feature/**
    paths:
      - "services/user-service/**"

  pull_request:
    branches:
      - main
    paths:
      - "services/user-service/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        working-directory: services/user-service
        run: npm install


      - name: Build Docker image
        working-directory: services/user-service
        run: |
          docker build -t skymonil/user-service:${{ github.sha }} .

      # âœ… Push ONLY on main branch
      - name: Login to DockerHub
        if: github.ref == 'refs/heads/main'
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin

      - name: Push image
        if: github.ref == 'refs/heads/main'
        run: |
          docker push skymonil/user-service:${{ github.sha }}
